{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?dataset_uri ?metadata_read ?metadata_edit ?metadata_remove ?name ?uuid

WHERE {
  GRAPH <{{state_graph}}> {
    ?collaborator_uri  djht:dataset             ?dataset_uri .
    ?collaborator_uri  rdf:type                 djht:Collaborator .
    ?collaborator_uri  djht:metadata_read       ?metadata_read .
    ?collaborator_uri  djht:metadata_edit       ?metadata_edit .
    ?collaborator_uri  djht:metadata_remove     ?metadata_remove .
    ?collaborator_uri  djht:name                ?name .

    BIND(STRAFTER(STR(?collaborator_uri), "collaborator:") AS ?uuid)
  }

FILTER (?dataset_uri = <dataset:{{dataset_uuid}}>)
}
{% endblock %}
