{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?log_entry ?created
WHERE {
  GRAPH <{{state_graph}}> {
    ?log_entry a djht:LogEntry .
    ?log_entry djht:event_type  ?event_type .
    ?log_entry djht:created ?created . 
    ?log_entry djht:dataset ?container_id .
  }
{% if filters is not none %}{{ filters | safe }}
{% endif %}
}
{% endblock %}
